export type AspectRatio = "1:1" | "4:5" | "9:16" | "1.91:1";

export type CarouselMode = "organic" | "meta-ads";

export type MetaAdCta =
  | "SHOP_NOW"
  | "LEARN_MORE"
  | "SIGN_UP"
  | "CONTACT_US"
  | "BOOK_NOW"
  | "DOWNLOAD"
  | "GET_OFFER";

export const META_AD_CTA_LABELS: Record<MetaAdCta, string> = {
  SHOP_NOW: "Shop Now",
  LEARN_MORE: "Learn More",
  SIGN_UP: "Sign Up",
  CONTACT_US: "Contact Us",
  BOOK_NOW: "Book Now",
  DOWNLOAD: "Download",
  GET_OFFER: "Get Offer",
};

export interface AdCopy {
  headline: string;       // max 40 chars
  description?: string;   // max 25 chars
  destinationUrl?: string;
}

export interface Slide {
  id: string;
  html: string;
  previousVersions: string[];
  order: number;
  notes: string;
  adCopy?: AdCopy;        // populated in meta-ads mode
}

export interface ReferenceImage {
  id: string;
  url: string;                    // e.g. "/uploads/abc.png"
  absPath: string;                // absolute path for Claude to Read
  name: string;                   // original filename or description
  addedAt: string;
  description?: string;           // Verbal description generated by Claude vision
  embedding?: number[];           // Normalized term-frequency vector for similarity search
  embeddingVocab?: string[];      // Ordered vocabulary keys corresponding to embedding dimensions
}

export interface CarouselFontSettings {
  headingFamily: string;
  bodyFamily: string;
  headingSize: number;    // px, e.g. 72
  bodySize: number;       // px, e.g. 18
  headingWeight: number;  // 300 | 400 | 500 | 600 | 700 | 800
  bodyWeight: number;
  letterSpacing: number;  // em, e.g. -0.02 to 0.1
  lineHeight: number;     // multiplier, e.g. 1.3
  textTransform: "none" | "uppercase" | "capitalize" | "lowercase";
}

export const DEFAULT_FONT_SETTINGS: CarouselFontSettings = {
  headingFamily: "Inter",
  bodyFamily: "Inter",
  headingSize: 72,
  bodySize: 18,
  headingWeight: 700,
  bodyWeight: 400,
  letterSpacing: 0,
  lineHeight: 1.3,
  textTransform: "none",
};

export interface Carousel {
  id: string;
  name: string;
  aspectRatio: AspectRatio;
  slides: Slide[];
  referenceImages: ReferenceImage[];
  mediaImageIds?: string[];
  caption?: string;
  hashtags?: string[];
  chatSessionId: string | null;
  /** Accumulated AI cost in USD across all chat turns */
  costUsd?: number;
  /** Per-carousel typography settings applied at render time */
  fontSettings?: CarouselFontSettings;
  isTemplate: boolean;
  tags: string[];
  createdAt: string;
  updatedAt: string;
  // Meta Ads fields
  mode: CarouselMode;
  adPrimaryText?: string;  // overall ad primary text, max 125 chars
  adCta?: MetaAdCta;
}

export interface CarouselsData {
  carousels: Carousel[];
}

export const DIMENSIONS: Record<AspectRatio, { width: number; height: number }> = {
  "1:1":    { width: 1080, height: 1080 },
  "4:5":    { width: 1080, height: 1350 },
  "9:16":   { width: 1080, height: 1920 },
  "1.91:1": { width: 1200, height: 628  },
};

export const MAX_SLIDES = 20;
export const MAX_VERSIONS = 5;
export const BUDGET_WARNING_USD = 5.0;
