/** A single image in the media library */
export interface MediaImage {
  id: string;
  url: string;          // e.g. "/uploads/abc.png"
  absPath: string;      // absolute path for Claude to Read
  name: string;         // original filename
  uploadedAt: string;
  /** Verbal description generated by Claude vision */
  description?: string;
  /** Normalized term-frequency vector for similarity search */
  embedding?: number[];
  /** Ordered vocabulary keys corresponding to embedding dimensions */
  embeddingVocab?: string[];
}

/** Global media library (all uploaded images across the app) */
export interface MediaLibraryData {
  images: MediaImage[];
}
